theme: jekyll-theme-minimal
title: Shawn Manriquez's homepage
description: ________________________________________________
description: My name is Shawn Manriquez, and this is my GitHub page. I am a computer systems engineering major at Boise State University. 
description: __________________________________________________
